PREFIX ftafmea: <http://onto.fel.cvut.cz/ontologies/fta-fmea-application/>

SELECT ?otherBehavior WHERE {
    ?behavior a ?behaviorType.
    ?behavior ftafmea:requires/ftafmea:requires+ ?otherBehavior.
}