server:
  port: 9999

repository:
  url: http://localhost/ava/services/db-server/repositories/fta-fmea


persistence:
  driver: cz.cvut.kbss.ontodriver.rdf4j.Rdf4jDataSource
  language: cs

security:
  provider: internal

appContext: http://localhost:5173
oidc.RoleClaim: realm_access.roles
cors.allowedOrigins: "http://localhost:5173,http://localhost:4173"

logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%X{username}] [thread] %-5level %logger{36} - %msg %n%throwable"
  level:
    root: INFO
    cz.cvut.kbss: INFO
    org.springframework.web: INFO

annotator:
  list-documents-api: ${LIST_DOCUMENT_API:http://localhost:8282/s-pipes/service?_pId=list-documents}
  convert-document-api: ${CONVERT_DOCUMENT_API:http://localhost:8282/s-pipes/service?_pId=convert-document}
  process-annotatoins-api: ${PROCESS_ANNOTATION_API:https://localhost:8090/annotator/process-annotation-service.sh}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost/ava/services/auth/realms/record-manager
          jwt-set-uri: http://localhost/ava/services/auth/realms/record-manager/protocol/openid-connect/certs


operational.data.filter:
  min-operational-hours: 200

operationalDataServer: https://kbss.felk.cvut.cz/ava/services/ava-analytics/stats/
operationaDataServerCheck: check
operationalFailureRateService: failure-rate