server:
  port: 9999

repository:
  url: http://localhost:7200/repositories/fta-fmea-02
  username: fta-fmea
  password: pass

persistence:
  driver: cz.cvut.kbss.ontodriver.sesame.SesameDataSource
  language: cs

security:
  jwt:
    secretKey: lwrUj5PmCE6X8ekbLd9wDTRlBkEJA0HB
    expiryMs: 28800000 # 8 hours

logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%X{username}] [thread] %-5level %logger{36} - %msg %n%throwable"
  level:
    root: INFO
    cz.cvut.kbss: INFO
    org.springframework.web: INFO