server:
  port: 9999

repository:
  url: http://localhost/ava/services/db-server/repositories/fta-fmea


persistence:
  driver: cz.cvut.kbss.ontodriver.rdf4j.Rdf4jDataSource
  language: cs

security:
  provider: internal
  cors.allowedOrigins: "http://localhost:5173,http://localhost:4173"
  oidc.RoleClaim: realm_access.roles

appContext: http://localhost:5173

logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%X{username}] [thread] %-5level %logger{36} - %msg %n%throwable"
  level:
    root: INFO
    cz.cvut.kbss: INFO
    org.springframework.web: INFO

management:
  endpoints.web.exposure.include: health

annotator:
  list-documents-api: ${LIST_DOCUMENT_API:http://localhost:8282/s-pipes/service?_pId=list-documents}
  convert-document-api: ${CONVERT_DOCUMENT_API:http://localhost:8282/s-pipes/service?_pId=convert-document}
  process-annotatoins-api: ${PROCESS_ANNOTATION_API:https://localhost:8090/annotator/process-annotation-service.sh}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost/ava/services/auth/realms/record-manager
          jwt-set-uri: http://localhost/ava/services/auth/realms/record-manager/protocol/openid-connect/certs


operational.data.filter:
  min-operational-hours: 200

operationalFailureRateService: http://localhost:9998/stats/failure-rate
fhaBasedoperationalFailureRateService: http://localhost:9998/stats/fha-failure-rate

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html

api:
  base-url: http://localhost:9999