POST {{host}}/auth/register
Content-Type: application/ld+json

{
  "username": "jakub",
  "password": "heslicko",
  "types": [
    "http://xmlns.com/foaf/0.1/Person"
  ],
  "@context": {
    "iri": "@id",
    "username": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/hasUsername",
    "password": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/hasPassword",
    "types": "@type"
  }
}

###
POST {{host}}/auth/signin
Content-Type: application/json

{
  "username": "jakub",
  "password": "heslicko"
}


###
PUT {{host}}/auth/current
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "username": "jakub",
  "password": "heslicko",
  "newPassword": "heslo"
}