GET {{host}}/failureModes
Authorization: Bearer {{jwt}}


###
POST {{host}}/failureModes
Content-Type: application/ld+json
Authorization: Bearer {{jwt}}

{
  "manifestingNode": {
    "treeNodeType": "EVENT",
    "event": {
      "name": "Pump not working",
      "description": "Pump cannot push the fuel to the engine",
      "eventType": "TOP_EVENT",
      "riskPriorityNumber": {
        "probability": 0.5,
        "severity": 4,
        "detection": 1,
        "types": ["http://onto.fel.cvut.cz/ontologies/fta-fmea-application/RiskPriorityNumber"]
      },
      "types": ["http://onto.fel.cvut.cz/ontologies/fta-fmea-application/FaultEvent"]
    },
    "types": ["http://onto.fel.cvut.cz/ontologies/fta-fmea-application/TreeNode"]
  },
  "types": [
    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/FailureMode"
  ],
  "@context": {
    "name": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/hasName",
    "description": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/hasDescription",
    "riskPriorityNumber": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/hasRPN",
    "probability": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/hasProbability",
    "severity": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/hasSeverity",
    "detection": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/hasDetection",
    "manifestingNode": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/isManifestedBy",
    "event": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/holds",
    "treeNodeType": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/hasTreeNodeType",
    "eventType": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/hasFaultEventType",
    "types": "@type"
  }
}


###
GET {{host}}/failureModes/{{failureModeFragment}}/mitigation
Authorization: Bearer {{jwt}}


###
POST {{host}}/failureModes/{{failureModeFragment}}/mitigation
Content-Type: application/ld+json
Authorization: Bearer {{jwt}}

{
  "name": "Better Materials",
  "description": "Usage of material XY",
  "types": [
    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/Mitigation"
  ],
  "@context": {
    "name": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/hasName",
    "description": "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/hasDescription",
    "types": "@type"
  }
}