GET {{host}}/failureModes/
Content-Type: application/json
Authorization: Bearer {{jwt}}


###
POST {{host}}/failureModes/
Content-Type: application/ld+json
Authorization: Bearer {{jwt}}

{
    "@type": [
      "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/FailureMode"
    ],
    "http://onto.fel.cvut.cz/ontologies/fta-fmea-application/hasName": "Failure Mode Number - 69"
  }