###
GET {{host}}/functions/{{functionFragment}}/failureModes
Authorization: Bearer {{jwt}}


###
POST {{host}}/functions/{{functionFragment}}/failureModes
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "uri": {{prefix}}{{componentFragment}}
}